ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'PENDING_PAYMENT';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'PENDING_DISPENSE';
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'DISPENSED';

ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "dispensedAt" TIMESTAMP(3);
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "dispensedById" INTEGER;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "dispensedByUsername" TEXT;
